name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Waiting for MongoDB to start
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB to start..."
            sleep 2
          done
          echo "MongoDB started"
      - name: Seed MongoDB
        working-directory: ./backend
        run: |
          npm install
          node seedTasksData.js
  test:
    runs-on: ubuntu-latest
    needs: mongo-init
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install
      - name: Run Frontend Tests
        working-directory: ./frontend
        run: npm test -- --watchAll=false
