name: MERN CI

on:
  push:
    branches: [main]

jobs:
  mongo-init-tests:
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      MONGO_URI: mongodb://mongo:27017/todo
    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Waiting for MongoDB to start
        run: |
          until nc -z localhost 27017; do
            echo "Waiting for MongoDB to start..."
            sleep 2
          done
          echo "MongoDB started"
      - name: Seed MongoDB
        working-directory: ./backend
        run: |
          npm install
          node seedTasksData.js
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test
